### PR TITLE
 Legacy browsers

### PR DESCRIPTION
**Pull request by dextel2**
+ Replaced `let` with `var` as it did not supported legacy browsers such as Safari > 9.5

### CODE REVIEW

**Comment by dextel2** [comment]
@tommymcglynn I'd appreciate if you merge this as this is failing in Safari > 9.5 and I have access to MavOS 10.5 and Safari 9.5, Even after adding polyfills it is still failing.

Regards,
Yash Karanke

**Comment by tommymcglynn** [comment]
@dextel2 Can you please remove the unnecessary indentation changes so the diff is isolated to the actual changes?

**Comment by dextel2** [comment]
@tommymcglynn sure, your indentation is 4 spaces, right?

**Comment by tommymcglynn** [comment]
@dextel2 Correct

**Comment by dextel2** [comment]
@tommymcglynn Please review PR.

**Pull request merged**
